import convert_json_to_corpus_shortArguments_procon
import convert_json_to_corpus_longArguments_procon
import convert_json_to_corpus_debatabase
import combine_corpus

convert_json_to_corpus_shortArguments_procon()
convert_json_to_corpus_longArguments_procon()
convert_json_to_corpus_debatabase()
combine_corpus()